<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace app\models;

/**
 * Description of Xml
 *
 * @author Larry
 */
class Xml {
    function imprimir_etiqueta($arg){
        //http://190.86.194.73:38080/conecta2/seam/resource/restv1/admision_envios/etiquetas
      return  $xml="<ETIQUETAS>
<ETIQUETA>
<NUMERO_ENVIO>{$arg['etiqueta']}</NUMERO_ENVIO>
<TIPO_IMPRESORA>L</TIPO_IMPRESORA>
</ETIQUETA>
<ETIQUETA><!-- Devuelve térmica-->
<NUMERO_ENVIO>{$arg['etiqueta']}</NUMERO_ENVIO>
<TIPO_IMPRESORA>T</TIPO_IMPRESORA>
</ETIQUETA>
<ETIQUETA><!-- Devuelve térmica-->
<NUMERO_ENVIO>{$arg['etiqueta']}</NUMERO_ENVIO>
</ETIQUETA>
</ETIQUETAS>";
    }
    function admisiones($arg){
       return $xml = "<ADMISIONES>
	<ADMISION>
		<GRABAR_ENVIO>S</GRABAR_ENVIO>
		<CODIGO_ADMISION>123</CODIGO_ADMISION>
		<NUMERO_ENVIO/>
		<NUMERO_BULTOS>{$arg['NUMERO_DE BULTOS']}</NUMERO_BULTOS>
		<CLIENTE_REMITENTE>{$arg['CLIENTE_REMITENTE']}</CLIENTE_REMITENTE>
		<CENTRO_REMITENTE>{$arg['CENTRO_REMITENTE']}</CENTRO_REMITENTE>
		<NOMBRE_REMITENTE>{$arg['NOMBRE_REMITENTE']}</NOMBRE_REMITENTE>
		<DIRECCION_REMITENTE>{$arg['DIRECCION_REMITENTE']}</DIRECCION_REMITENTE >
		<PAIS_REMITENTE>{$arg['PAIS_REMITENTE']}</PAIS_REMITENTE>
		<CODIGO_POSTAL_REMITENTE>{$arg['CODIGO_POSTAL_REMITENTE']}</CODIGO_POSTAL_REMITENTE>
		<POBLACION_REMITENTE>{$arg['POBLACION_REMITENTE']}</POBLACION_REMITENTE>
		<TIPO_DOC_REMITENTE>{$arg['TIPO_DOC_REMITENTE']}</TIPO_DOC_REMITENTE>
		<DOCUMENTO_IDENTIDAD_REMITENTE>{$arg['DOCUMENTO_IDENTIDAD_REMITENTE']}</DOCUMENTO_IDENTIDAD_REMITENTE>
		<PERSONA_CONTACTO_REMITENTE>{$arg['PERSONA_CONTACTO_REMITENTE']}</PERSONA_CONTACTO_REMITENTE>
		<TELEFONO_CONTACTO_REMITENTE>{$arg['TELEFONO_CONTACTO_REMITENTE']}</TELEFONO_CONTACTO_REMITENTE>
		<DEPARTAMENTO_REMITENTE>{$arg['DEPARTAMENTO_REMITENTE']}</DEPARTAMENTO_REMITENTE>
		<EMAIL_REMITENTE>{$arg['EMAIL_REMITENTE']}</EMAIL_REMITENTE>
		<CLIENTE_DESTINATARIO>00010795</CLIENTE_DESTINATARIO>
		<CENTRO_DESTINATARIO>01</CENTRO_DESTINATARIO>
		<NOMBRE_DESTINATARIO>{$arg['NOMBRE_DESTINATARIO']}</NOMBRE_DESTINATARIO>
		<DIRECCION_DESTINATARIO>{$arg['DIRECCION_DESTINATARIO']}</DIRECCION_DESTINATARIO>
		<PAIS_DESTINATARIO>057</PAIS_DESTINATARIO>
		<CODIGO_POSTAL_DESTINATARIO>110911</CODIGO_POSTAL_DESTINATARIO>
		<POBLACION_DESTINATARIO>BOGOTA</POBLACION_DESTINATARIO>
		<TIPO_DOC_DESTINATARIO>CC</TIPO_DOC_DESTINATARIO>
		<DOCUMENTO_IDENTIDAD_DESTINATARIO>73082468Z</DOCUMENTO_IDENTIDAD_DESTINATARIO>
		<PERSONA_CONTACTO_DESTINATARIO>{$arg['PERSONA_CONTACTO_DESTINATARIO']}</PERSONA_CONTACTO_DESTINATARIO >
		<TELEFONO_CONTACTO_DESTINATARIO>{$arg['TELEFONO_CONTACTO_DESTINATARIO']}</TELEFONO_CONTACTO_DESTINATARIO>
		<DEPARTAMENTO_DESTINATARIO>{$arg['DEPARTAMENTO_DESTINATARIO']}</DEPARTAMENTO_DESTINATARIO>
		<EMAIL_DESTINATARIO>{$arg['EMAIL_DESTINATARIO']}</EMAIL_DESTINATARIO>
		<INCOTERM>FCA</INCOTERM>
		<RAZON_EXPORTAR>01</RAZON_EXPORTAR>
		<EMBALAJE>EV</EMBALAJE>
		<CODIGO_SERVICIO>3005</CODIGO_SERVICIO>
		<KILOS>4</KILOS>
		<VOLUMEN>0.5</VOLUMEN>
		<LARGO>10</LARGO>
		<ANCHO>20</ANCHO>
		<ALTO>15</ALTO>
		<NUMERO_REFERENCIA>{$arg['EMAIL_DESTINATARIO']}</NUMERO_REFERENCIA>
		<IMPORTE_REEMBOLSO>100000</IMPORTE_REEMBOLSO>
		<IMPORTE_VALOR_DECLARADO>1000</IMPORTE_VALOR_DECLARADO>
		<TIPO_PORTES>P</TIPO_PORTES>
		<OBSERVACIONES1>Prueba de grabación en WEEX</OBSERVACIONES1>
		<OBSERVACIONES2>OBS2</OBSERVACIONES2>
		<TIPO_MERCANCIA>P</TIPO_MERCANCIA>
		<!--CRR_DESTINO>BOGTCG</CRR_DESTINO-->
		<ASEGURAR_ENVIO>S</ASEGURAR_ENVIO>
		<TIPO_MONEDA>COP</TIPO_MONEDA>
	</ADMISION>
</ADMISIONES>";
        
        /*return "<ADMISIONES>
	<ADMISION>
		<GRABAR_ENVIO>S</GRABAR_ENVIO>
		<CODIGO_ADMISION>123</CODIGO_ADMISION>
		<NUMERO_ENVIO/>
                <NUMERO_BULTOS>{$arg['NUMERO_DE BULTOS']}</NUMERO_BULTOS>
		<CLIENTE_REMITENTE>{$arg['CLIENTE_REMITENTE']}</CLIENTE_REMITENTE>
		<CENTRO_REMITENTE>{$arg['CENTRO_REMITENTE']}</CENTRO_REMITENTE>
		<NOMBRE_REMITENTE>{$arg['NOMBRE_REMITENTE']}</NOMBRE_REMITENTE>
		<DIRECCION_REMITENTE>{$arg['DIRECCION_REMITENTE']}</DIRECCION_REMITENTE >
		<PAIS_REMITENTE>{$arg['PAIS_REMITENTE']}</PAIS_REMITENTE>
		<CODIGO_POSTAL_REMITENTE>{$arg['CODIGO_POSTAL_REMITENTE']}</CODIGO_POSTAL_REMITENTE>
		<POBLACION_REMITENTE>{$arg['POBLACION_REMITENTE']}</POBLACION_REMITENTE>
		<TIPO_DOC_REMITENTE>{$arg['TIPO_DOC_REMITENTE']}</TIPO_DOC_REMITENTE>
		<DOCUMENTO_IDENTIDAD_REMITENTE>{$arg['DOCUMENTO_IDENTIDAD_REMITENTE']}</DOCUMENTO_IDENTIDAD_REMITENTE>
		<PERSONA_CONTACTO_REMITENTE>{$arg['PERSONA_CONTACTO_REMITENTE']}</PERSONA_CONTACTO_REMITENTE>
		<TELEFONO_CONTACTO_REMITENTE>{$arg['TELEFONO_CONTACTO_REMITENTE']}</TELEFONO_CONTACTO_REMITENTE>
		<DEPARTAMENTO_REMITENTE>{$arg['DEPARTAMENTO_REMITENTE']}</DEPARTAMENTO_REMITENTE>
		<EMAIL_REMITENTE>{$arg['EMAIL_REMITENTE']}</EMAIL_REMITENTE>
		<CLIENTE_DESTINATARIO>{$arg['CLIENTE_DESTINATARIO']}</CLIENTE_DESTINATARIO>
		<CENTRO_DESTINATARIO>{$arg['CENTRO_DESTINATARIO']}</CENTRO_DESTINATARIO>
		<NOMBRE_DESTINATARIO>{$arg['NOMBRE_DESTINATARIO']}</NOMBRE_DESTINATARIO>
		<DIRECCION_DESTINATARIO>{$arg['DIRECCION_DESTINATARIO']}</DIRECCION_DESTINATARIO>
		<PAIS_DESTINATARIO>{$arg['PAIS_DESTINATARIO']}</PAIS_DESTINATARIO>
		<CODIGO_POSTAL_DESTINATARIO>{$arg['CODIGO_POSTAL_DESTINATARIO']}</CODIGO_POSTAL_DESTINATARIO>
		<POBLACION_DESTINATARIO>{$arg['POBLACION_DESTINATARIO']}</POBLACION_DESTINATARIO>
		<TIPO_DOC_DESTINATARIO>{$arg['TIPO_DOC_DESTINATARIO']}</TIPO_DOC_DESTINATARIO>
		<DOCUMENTO_IDENTIDAD_DESTINATARIO>{$arg['DOCUMENTO_IDENTIDAD_DESTINATARIO']}</DOCUMENTO_IDENTIDAD_DESTINATARIO>
		<PERSONA_CONTACTO_DESTINATARIO>{$arg['PERSONA_CONTACTO_DESTINATARIO']}</PERSONA_CONTACTO_DESTINATARIO >
		<TELEFONO_CONTACTO_DESTINATARIO>{$arg['TELEFONO_CONTACTO_DESTINATARIO']}</TELEFONO_CONTACTO_DESTINATARIO>
		<DEPARTAMENTO_DESTINATARIO>{$arg['DEPARTAMENTO_DESTINATARIO']}</DEPARTAMENTO_DESTINATARIO>
		<EMAIL_DESTINATARIO>{$arg['EMAIL_DESTINATARIO']}</EMAIL_DESTINATARIO>
		<INCOTERM>FCA</INCOTERM>
		<RAZON_EXPORTAR>01</RAZON_EXPORTAR>
		<EMBALAJE>EV</EMBALAJE>
		<CODIGO_SERVICIO>{$arg['CODIGO_SERVICIO']}</CODIGO_SERVICIO>
		<KILOS>{$arg['KILOS']}</KILOS>
		<VOLUMEN>{$arg['VOLUMEN']}</VOLUMEN>
		<LARGO>{$arg['LARGO']}</LARGO>
		<ANCHO>{$arg['ANCHO']}</ANCHO>
		<ALTO>{$arg['ALTO']}</ALTO>
		<NUMERO_REFERENCIA>{$arg['NUMERO_REFERENCIA']}</NUMERO_REFERENCIA>
		<IMPORTE_REEMBOLSO>{$arg['IMPORTE_REEMBOLSO']}</IMPORTE_REEMBOLSO>
		<IMPORTE_VALOR_DECLARADO>{$arg['IMPORTE_VALOR_DECLARADO']}</IMPORTE_VALOR_DECLARADO>
		<TIPO_PORTES>P</TIPO_PORTES>
		<OBSERVACIONES1>{$arg['OBSERVACIONES1']}</OBSERVACIONES1>
		<OBSERVACIONES2>{$arg['OBSERVACIONES2']}</OBSERVACIONES2>
		<TIPO_MERCANCIA>{$arg['TIPO_MERCANCIA']}</TIPO_MERCANCIA>
		<!--CRR_DESTINO>BOGTCG</CRR_DESTINO-->
		<ASEGURAR_ENVIO>S</ASEGURAR_ENVIO>
		<TIPO_MONEDA>{$arg['TIPO_MONEDA']}</TIPO_MONEDA>
	</ADMISION>
         * t o l respuesta va a ser en base 64
</ADMISIONES>";*///00010795 labelary.com / base64.guru / lear base 64
        //00008493 53
        $xml = "<ADMISIONES>
	<ADMISION>
		<GRABAR_ENVIO>S</GRABAR_ENVIO>
		<CODIGO_ADMISION>123</CODIGO_ADMISION>
		<NUMERO_ENVIO/>
		<NUMERO_BULTOS>{$arg['NUMERO_DE BULTOS']}</NUMERO_BULTOS>//numero de piezas (es una caja)
		<CLIENTE_REMITENTE>00010795</CLIENTE_REMITENTE>
		<CENTRO_REMITENTE>01</CENTRO_REMITENTE>
		<NOMBRE_REMITENTE></NOMBRE_REMITENTE>
		<DIRECCION_REMITENTE>PRUEBA PASEO</DIRECCION_REMITENTE >
		<PAIS_REMITENTE>057</PAIS_REMITENTE>
		<CODIGO_POSTAL_REMITENTE>110911</CODIGO_POSTAL_REMITENTE>
		<POBLACION_REMITENTE>BOGOTA</POBLACION_REMITENTE>
		<TIPO_DOC_REMITENTE>CC</TIPO_DOC_REMITENTE>
		<DOCUMENTO_IDENTIDAD_REMITENTE>73082468Z</DOCUMENTO_IDENTIDAD_REMITENTE>
		<PERSONA_CONTACTO_REMITENTE>Jeison Ricardo</PERSONA_CONTACTO_REMITENTE>
		<TELEFONO_CONTACTO_REMITENTE>1234</TELEFONO_CONTACTO_REMITENTE>
		<DEPARTAMENTO_REMITENTE>Dpto de origen</DEPARTAMENTO_REMITENTE>
		<EMAIL_REMITENTE>aaa@ori.com</EMAIL_REMITENTE>
		<CLIENTE_DESTINATARIO>999999999</CLIENTE_DESTINATARIO>
		<CENTRO_DESTINATARIO>99</CENTRO_DESTINATARIO>
		<NOMBRE_DESTINATARIO>nombre variable</NOMBRE_DESTINATARIO>
		<DIRECCION_DESTINATARIO>Carrera 30 #57-17</DIRECCION_DESTINATARIO>
		<PAIS_DESTINATARIO>057</PAIS_DESTINATARIO>
		<CODIGO_POSTAL_DESTINATARIO>{$arg['CODIGO_POSTAL_DESTINATARIO']}</CODIGO_POSTAL_DESTINATARIO>
		<POBLACION_DESTINATARIO>{$arg['POBLACION_DESTINATARIO']}</POBLACION_DESTINATARIO>
		<TIPO_DOC_DESTINATARIO>CC</TIPO_DOC_DESTINATARIO>
		<DOCUMENTO_IDENTIDAD_DESTINATARIO>73082468Z</DOCUMENTO_IDENTIDAD_DESTINATARIO>
		<PERSONA_CONTACTO_DESTINATARIO>R R</PERSONA_CONTACTO_DESTINATARIO >
		<TELEFONO_CONTACTO_DESTINATARIO>432242</TELEFONO_CONTACTO_DESTINATARIO>
		<DEPARTAMENTO_DESTINATARIO>Dpto. de destino</DEPARTAMENTO_DESTINATARIO>
		<EMAIL_DESTINATARIO>leireoo@gmail.com</EMAIL_DESTINATARIO>
		<INCOTERM>FCA</INCOTERM>
		<RAZON_EXPORTAR>01</RAZON_EXPORTAR>
		<EMBALAJE>EV</EMBALAJE>
		<CODIGO_SERVICIO>3005</CODIGO_SERVICIO>
		<KILOS>4</KILOS>
		<VOLUMEN>0.5</VOLUMEN>
		<LARGO>10</LARGO>
		<ANCHO>20</ANCHO>
		<ALTO>15</ALTO>
		<NUMERO_REFERENCIA>1234</NUMERO_REFERENCIA>//de shopify numero de orden
		<IMPORTE_REEMBOLSO>100000</IMPORTE_REEMBOLSO>
		<IMPORTE_VALOR_DECLARADO>1000</IMPORTE_VALOR_DECLARADO>
		<TIPO_PORTES>P</TIPO_PORTES>
		<OBSERVACIONES1>Prueba de grabación en WEEX</OBSERVACIONES1>
		<OBSERVACIONES2>OBS2</OBSERVACIONES2>
		<TIPO_MERCANCIA>P</TIPO_MERCANCIA>
		<!--CRR_DESTINO>BOGTCG</CRR_DESTINO-->
		<ASEGURAR_ENVIO>S</ASEGURAR_ENVIO>
		<TIPO_MONEDA>COP</TIPO_MONEDA>
	</ADMISION>
</ADMISIONES>";
    }
    
}
